name: Deploy Svelte to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger the action on pushes to the main branch

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.18.0'  # Specify Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build Svelte site
        run: npm run build  # Ensure your package.json has a "build" script

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./.svelte-kit  # Adjust this to your build output directory

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v4.0.5
            
